---
name: Deploy to staging
on:
  push:
    branches: [main]
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: SSH Into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key root@64.227.172.68 -t "cd
          cd ci-next-app && git pull origin main && sudo -s && npm install -g pnpm && pnpm install && pnpm run build &&
          pm2 restart fe-server && pm2 restart http-server && pm2 restart ws-server"
          
          
          
          
          
