name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install -g pnpm

    - name: Build and deploy
      run: |
        ssh -i ~/ssh_key root@64.227.172.68 -t "
        cd ci-next-app/ &&
        git pull origin main &&
        export PATH=/root/.nvm/versions/node/v16.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin &&
        pnpm install &&
        pnpm run build &&
        pm2 restart fe-server &&
        pm2 restart http-server &&
        pm2 restart ws-server"